export enum BookGenre {
  FICTION = "FICTION",
  NON_FICTION = "NON_FICTION",
  MYSTERY = "MYSTERY",
  ROMANCE = "ROMANCE",
  SCIENCE_FICTION = "SCIENCE_FICTION",
  FANTASY = "FANTASY",
  BIOGRAPHY = "BIOGRAPHY",
  SELF_HELP = "SELF_HELP",
  HISTORY = "HISTORY",
  HORROR = "HORROR",
  OTHERS = "OTHERS",
}
